//
// AddItemToBookmarkFolderRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AddItemToBookmarkFolderRequest: Codable, JSONEncodable, Hashable {

    public var item: Int64?
    public var folder: Int64?

    public init(item: Int64? = nil, folder: Int64? = nil) {
        self.item = item
        self.folder = folder
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case item
        case folder
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(item, forKey: .item)
        try container.encodeIfPresent(folder, forKey: .folder)
    }
}

