//
// CheckboxSetting.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CheckboxSetting: Codable, JSONEncodable, Hashable {

    public var label: String?
    public var value: Int?

    public init(label: String? = nil, value: Int? = nil) {
        self.label = label
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

