//
// CollectionItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CollectionItem: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var title: String?
    public var watchers: Int64?
    public var views: Int64?
    public var created: Int64?
    public var updated: Int64?
    public var posters: Posters?

    public init(id: Int64? = nil, title: String? = nil, watchers: Int64? = nil, views: Int64? = nil, created: Int64? = nil, updated: Int64? = nil, posters: Posters? = nil) {
        self.id = id
        self.title = title
        self.watchers = watchers
        self.views = views
        self.created = created
        self.updated = updated
        self.posters = posters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case watchers
        case views
        case created
        case updated
        case posters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(watchers, forKey: .watchers)
        try container.encodeIfPresent(views, forKey: .views)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encodeIfPresent(updated, forKey: .updated)
        try container.encodeIfPresent(posters, forKey: .posters)
    }
}

