//
// CollectionsSortingDESC.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum CollectionsSortingDESC: String, Codable, CaseIterable {
    case id = "id-"
    case title = "title-"
    case created = "created-"
    case updated = "updated-"
    case views = "views-"
    case watchers = "watchers-"
}
