//
// FullItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum FullItem: Codable, JSONEncodable, Hashable {
    case typeMovieItem(MovieItem)
    case typeSerialItem(SerialItem)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeMovieItem(let value):
            try container.encode(value)
        case .typeSerialItem(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(MovieItem.self) {
            self = .typeMovieItem(value)
        } else if let value = try? container.decode(SerialItem.self) {
            self = .typeSerialItem(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of FullItem"))
        }
    }
}

