//
// GeneralError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GeneralError: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var message: String?
    public var code: Int64?
    public var status: Int64?

    public init(name: String? = nil, message: String? = nil, code: Int64? = nil, status: Int64? = nil) {
        self.name = name
        self.message = message
        self.code = code
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case message
        case code
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

