//
// GetBookmarkItems200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetBookmarkItems200Response: Codable, JSONEncodable, Hashable {

    public var folder: BookmarkFolder?
    public var items: [ItemInfo]?

    public init(folder: BookmarkFolder? = nil, items: [ItemInfo]? = nil) {
        self.folder = folder
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case folder
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(folder, forKey: .folder)
        try container.encodeIfPresent(items, forKey: .items)
    }
}

