//
// GetCollectionListSortParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetCollectionListSortParameter: Codable, JSONEncodable, Hashable {
    case typeCollectionsSortingASC(CollectionsSortingASC)
    case typeCollectionsSortingDESC(CollectionsSortingDESC)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeCollectionsSortingASC(let value):
            try container.encode(value)
        case .typeCollectionsSortingDESC(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(CollectionsSortingASC.self) {
            self = .typeCollectionsSortingASC(value)
        } else if let value = try? container.decode(CollectionsSortingDESC.self) {
            self = .typeCollectionsSortingDESC(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of GetCollectionListSortParameter"))
        }
    }
}

