//
// GetCollection200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCollection200Response: Codable, JSONEncodable, Hashable {

    public var collection: CollectionItem?
    public var items: [ItemInfo]?

    public init(collection: CollectionItem? = nil, items: [ItemInfo]? = nil) {
        self.collection = collection
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collection
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(collection, forKey: .collection)
        try container.encodeIfPresent(items, forKey: .items)
    }
}

