//
// GetDevicesList200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetDevicesList200Response: Codable, JSONEncodable, Hashable {

    public var devices: [Device]?

    public init(devices: [Device]? = nil) {
        self.devices = devices
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case devices
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(devices, forKey: .devices)
    }
}

