//
// GetItemsByFilterSortParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetItemsByFilterSortParameter: Codable, JSONEncodable, Hashable {
    case typeItemsSortingASC(ItemsSortingASC)
    case typeItemsSortingDESC(ItemsSortingDESC)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeItemsSortingASC(let value):
            try container.encode(value)
        case .typeItemsSortingDESC(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(ItemsSortingASC.self) {
            self = .typeItemsSortingASC(value)
        } else if let value = try? container.decode(ItemsSortingDESC.self) {
            self = .typeItemsSortingDESC(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of GetItemsByFilterSortParameter"))
        }
    }
}

