//
// GetItemsByFilterConditionsParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetItemsByFilterConditionsParameter: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var year: Int?
    public var title: String?
    public var created: Int64?
    public var updated: Int64?
    public var rating: Int?
    public var views: Int64?
    public var watchers: Int64?

    public init(id: Int64? = nil, year: Int? = nil, title: String? = nil, created: Int64? = nil, updated: Int64? = nil, rating: Int? = nil, views: Int64? = nil, watchers: Int64? = nil) {
        self.id = id
        self.year = year
        self.title = title
        self.created = created
        self.updated = updated
        self.rating = rating
        self.views = views
        self.watchers = watchers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case year
        case title
        case created
        case updated
        case rating
        case views
        case watchers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encodeIfPresent(updated, forKey: .updated)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(views, forKey: .views)
        try container.encodeIfPresent(watchers, forKey: .watchers)
    }
}

