//
// GetItemTrailer200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetItemTrailer200Response: Codable, JSONEncodable, Hashable {

    public var trailer: Trailer?

    public init(trailer: Trailer? = nil) {
        self.trailer = trailer
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case trailer
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(trailer, forKey: .trailer)
    }
}

