//
// GetItemComments200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetItemComments200Response: Codable, JSONEncodable, Hashable {

    public var comments: [Comment]?

    public init(comments: [Comment]? = nil) {
        self.comments = comments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(comments, forKey: .comments)
    }
}

