//
// GetMediaLinks200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMediaLinks200Response: Codable, JSONEncodable, Hashable {

    public var files: [File]?
    public var subtitles: [Subtitle]?

    public init(files: [File]? = nil, subtitles: [Subtitle]? = nil) {
        self.files = files
        self.subtitles = subtitles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case files
        case subtitles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(files, forKey: .files)
        try container.encodeIfPresent(subtitles, forKey: .subtitles)
    }
}

