//
// GetTvChannels200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTvChannels200Response: Codable, JSONEncodable, Hashable {

    public var channels: [TVChannel]?

    public init(channels: [TVChannel]? = nil) {
        self.channels = channels
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channels
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(channels, forKey: .channels)
    }
}

