//
// GetWatchingStatus200ResponseItemOneOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWatchingStatus200ResponseItemOneOf1: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var title: String?
    public var type: MovieType?
    public var videos: [VideoWatchingStatus]?

    public init(id: Int64? = nil, title: String? = nil, type: MovieType? = nil, videos: [VideoWatchingStatus]? = nil) {
        self.id = id
        self.title = title
        self.type = type
        self.videos = videos
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case type
        case videos
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(videos, forKey: .videos)
    }
}

