//
// GetWatchingStatus200ResponseItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetWatchingStatus200ResponseItem: Codable, JSONEncodable, Hashable {
    case typeGetWatchingStatus200ResponseItemOneOf(GetWatchingStatus200ResponseItemOneOf)
    case typeGetWatchingStatus200ResponseItemOneOf1(GetWatchingStatus200ResponseItemOneOf1)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeGetWatchingStatus200ResponseItemOneOf(let value):
            try container.encode(value)
        case .typeGetWatchingStatus200ResponseItemOneOf1(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(GetWatchingStatus200ResponseItemOneOf.self) {
            self = .typeGetWatchingStatus200ResponseItemOneOf(value)
        } else if let value = try? container.decode(GetWatchingStatus200ResponseItemOneOf1.self) {
            self = .typeGetWatchingStatus200ResponseItemOneOf1(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of GetWatchingStatus200ResponseItem"))
        }
    }
}

