//
// GetWatchingStatus200ResponseItemOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWatchingStatus200ResponseItemOneOf: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var title: String?
    public var type: SerialType?
    public var seasons: [SeasonWatchingStatus]?

    public init(id: Int64? = nil, title: String? = nil, type: SerialType? = nil, seasons: [SeasonWatchingStatus]? = nil) {
        self.id = id
        self.title = title
        self.type = type
        self.seasons = seasons
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case type
        case seasons
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(seasons, forKey: .seasons)
    }
}

