//
// HistoryItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HistoryItem: Codable, JSONEncodable, Hashable {

    public var time: Int?
    public var counter: Int?
    public var firstSeen: Int64?
    public var lastSeen: Int64?
    public var item: ItemInfo?
    public var media: HistoryItemMedia?

    public init(time: Int? = nil, counter: Int? = nil, firstSeen: Int64? = nil, lastSeen: Int64? = nil, item: ItemInfo? = nil, media: HistoryItemMedia? = nil) {
        self.time = time
        self.counter = counter
        self.firstSeen = firstSeen
        self.lastSeen = lastSeen
        self.item = item
        self.media = media
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case counter
        case firstSeen = "first_seen"
        case lastSeen = "last_seen"
        case item
        case media
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(counter, forKey: .counter)
        try container.encodeIfPresent(firstSeen, forKey: .firstSeen)
        try container.encodeIfPresent(lastSeen, forKey: .lastSeen)
        try container.encodeIfPresent(item, forKey: .item)
        try container.encodeIfPresent(media, forKey: .media)
    }
}

