//
// ItemInfoDuration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ItemInfoDuration: Codable, JSONEncodable, Hashable {

    public var average: Float?
    public var total: Float?

    public init(average: Float? = nil, total: Float? = nil) {
        self.average = average
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case average
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(average, forKey: .average)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

