//
// ModelType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ModelType: String, Codable, CaseIterable {
    case movie = "movie"
    case documovie = "documovie"
    case concert = "concert"
    case serial = "serial"
    case docuserial = "docuserial"
    case docu = "docu"
    case music = "music"
    case tvshow = "tvshow"
    case _3d = "3d"
    case _4k = "4k"
}
