//
// MovieType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum MovieType: String, Codable, CaseIterable {
    case movie = "movie"
    case documovie = "documovie"
    case concert = "concert"
}
