//
// NotifyDeviceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NotifyDeviceRequest: Codable, JSONEncodable, Hashable {

    public var title: String?
    public var hardware: String?
    public var software: String?

    public init(title: String? = nil, hardware: String? = nil, software: String? = nil) {
        self.title = title
        self.hardware = hardware
        self.software = software
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case hardware
        case software
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(hardware, forKey: .hardware)
        try container.encodeIfPresent(software, forKey: .software)
    }
}

