//
// Pagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Pagination: Codable, JSONEncodable, Hashable {

    public var total: Int64?
    public var current: Int64?
    public var perpage: Int64?

    public init(total: Int64? = nil, current: Int64? = nil, perpage: Int64? = nil) {
        self.total = total
        self.current = current
        self.perpage = perpage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case current
        case perpage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(current, forKey: .current)
        try container.encodeIfPresent(perpage, forKey: .perpage)
    }
}

