//
// RemoveDeviceById200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RemoveDeviceById200Response: Codable, JSONEncodable, Hashable {

    public var status: Int?
    public var current: Bool?

    public init(status: Int? = nil, current: Bool? = nil) {
        self.status = status
        self.current = current
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case current
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(current, forKey: .current)
    }
}

