//
// SearchItems200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SearchItems200Response: Codable, JSONEncodable, Hashable {
    case typeSearchItems200ResponseOneOf(SearchItems200ResponseOneOf)
    case typeSearchItems200ResponseOneOf1(SearchItems200ResponseOneOf1)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeSearchItems200ResponseOneOf(let value):
            try container.encode(value)
        case .typeSearchItems200ResponseOneOf1(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(SearchItems200ResponseOneOf.self) {
            self = .typeSearchItems200ResponseOneOf(value)
        } else if let value = try? container.decode(SearchItems200ResponseOneOf1.self) {
            self = .typeSearchItems200ResponseOneOf1(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of SearchItems200Response"))
        }
    }
}

