//
// SeasonWatchingStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SeasonWatchingStatus: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var number: Int64?
    public var status: Status?
    public var episodes: [EpisodeWatchingStatus]?

    public init(id: Int64? = nil, number: Int64? = nil, status: Status? = nil, episodes: [EpisodeWatchingStatus]? = nil) {
        self.id = id
        self.number = number
        self.status = status
        self.episodes = episodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case number
        case status
        case episodes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(episodes, forKey: .episodes)
    }
}

