//
// Season.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Season: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var number: Int?
    public var title: String?
    public var episodes: [Episode]?

    public init(id: Int64? = nil, number: Int? = nil, title: String? = nil, episodes: [Episode]? = nil) {
        self.id = id
        self.number = number
        self.title = title
        self.episodes = episodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case number
        case title
        case episodes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(episodes, forKey: .episodes)
    }
}

