//
// SelectSettingOption.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SelectSettingOption: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var label: String?
    public var description: String?
    public var selected: Int?

    public init(id: Int64? = nil, label: String? = nil, description: String? = nil, selected: Int? = nil) {
        self.id = id
        self.label = label
        self.description = description
        self.selected = selected
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case label
        case description
        case selected
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(selected, forKey: .selected)
    }
}

