//
// SerialType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SerialType: String, Codable, CaseIterable {
    case serial = "serial"
    case docuserial = "docuserial"
}
