//
// ServerLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerLocation: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var location: String?
    public var name: String?

    public init(id: Int64? = nil, location: String? = nil, name: String? = nil) {
        self.id = id
        self.location = location
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case location
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

