//
// Status.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Status: Int, Codable, CaseIterable {
    case number1 = -1
    case _0 = 0
    case _1 = 1
}
