//
// Subtitle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Subtitle: Codable, JSONEncodable, Hashable {

    public var lang: String?
    public var shift: Int64?
    public var embed: Bool?
    public var file: String?
    public var url: String?

    public init(lang: String? = nil, shift: Int64? = nil, embed: Bool? = nil, file: String? = nil, url: String? = nil) {
        self.lang = lang
        self.shift = shift
        self.embed = embed
        self.file = file
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lang
        case shift
        case embed
        case file
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lang, forKey: .lang)
        try container.encodeIfPresent(shift, forKey: .shift)
        try container.encodeIfPresent(embed, forKey: .embed)
        try container.encodeIfPresent(file, forKey: .file)
        try container.encodeIfPresent(url, forKey: .url)
    }
}

