//
// ToggleWatchList200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ToggleWatchList200Response: Codable, JSONEncodable, Hashable {

    public var status: Int?
    public var watching: Bool?

    public init(status: Int? = nil, watching: Bool? = nil) {
        self.status = status
        self.watching = watching
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case watching
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(watching, forKey: .watching)
    }
}

