//
// ToggleWatchedStatus200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ToggleWatchedStatus200Response: Codable, JSONEncodable, Hashable {

    public enum Watched: Int, Codable, CaseIterable {
        case _0 = 0
        case _1 = 1
    }
    public var status: Int?
    public var watched: Watched?

    public init(status: Int? = nil, watched: Watched? = nil) {
        self.status = status
        self.watched = watched
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case watched
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(watched, forKey: .watched)
    }
}

