//
// TVChannel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TVChannel: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var title: String?
    public var name: String?
    public var stream: String?
    public var logos: TVChannelLogos?

    public init(id: Int64? = nil, title: String? = nil, name: String? = nil, stream: String? = nil, logos: TVChannelLogos? = nil) {
        self.id = id
        self.title = title
        self.name = name
        self.stream = stream
        self.logos = logos
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case name
        case stream
        case logos
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(stream, forKey: .stream)
        try container.encodeIfPresent(logos, forKey: .logos)
    }
}

