//
// TypeAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TypeAllOf: String, Codable, CaseIterable {
    case docu = "docu"
    case music = "music"
    case tvshow = "tvshow"
    case _3d = "3d"
    case _4k = "4k"
}
