//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct User: Codable, JSONEncodable, Hashable {

    public var username: String?
    public var regDate: String?
    public var subscription: UserSubscription?
    public var profile: UserProfile?

    public init(username: String? = nil, regDate: String? = nil, subscription: UserSubscription? = nil, profile: UserProfile? = nil) {
        self.username = username
        self.regDate = regDate
        self.subscription = subscription
        self.profile = profile
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case regDate = "reg_date"
        case subscription
        case profile
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(regDate, forKey: .regDate)
        try container.encodeIfPresent(subscription, forKey: .subscription)
        try container.encodeIfPresent(profile, forKey: .profile)
    }
}

