//
// VideoQuality.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VideoQuality: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var title: String?
    public var quality: Int?

    public init(id: Int64? = nil, title: String? = nil, quality: Int? = nil) {
        self.id = id
        self.title = title
        self.quality = quality
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case quality
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(quality, forKey: .quality)
    }
}

