//
// WatchingMovie.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WatchingMovie: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var type: MovieType?
    public var subtype: String?
    public var title: String?
    public var posters: Posters?

    public init(id: Int64? = nil, type: MovieType? = nil, subtype: String? = nil, title: String? = nil, posters: Posters? = nil) {
        self.id = id
        self.type = type
        self.subtype = subtype
        self.title = title
        self.posters = posters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case subtype
        case title
        case posters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(subtype, forKey: .subtype)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(posters, forKey: .posters)
    }
}

