name: KinopubAuth
targets:
  KinopubAuth:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [KinopubAuth]
    info:
      path: ./Info.plist
      version: 1.3
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
